<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.AuddMusicRecognition</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.AuddMusicRecognition</AssemblyName>
    <Version>1.0.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AnalysisMode>Recommended</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="$(JellyfinVersion)">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="$(JellyfinVersion)">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\configPage.html" />
    <EmbeddedResource Include="..\..\web-client\audd-music-recognition.plugin.js" Link="Web\audd-music-recognition.plugin.js" LogicalName="Jellyfin.Plugin.AuddMusicRecognition.Web.audd-music-recognition.plugin.js" />
  </ItemGroup>
</Project>
